"""
Agent 5 — Test Generation.

Adds edge-case tests on top of the baseline suite shipped by codegen.
Kept deterministic for the same reproducibility reason as codegen.
"""
from __future__ import annotations
import os

EDGE_CASE_TESTS = '''"""Edge-case tests generated by the TestGen agent."""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from fastapi.testclient import TestClient
from app.main import app
from app.database import Base, engine

client = TestClient(app)


def _reset_db():
    Base.metadata.drop_all(bind=engine)
    Base.metadata.create_all(bind=engine)


def test_invalid_url_rejected():
    _reset_db()
    r = client.post("/api/shorten", json={"url": "not-a-valid-url"})
    assert r.status_code == 422


def test_analytics_for_unclicked_code_is_zero():
    _reset_db()
    r = client.post("/api/shorten", json={"url": "https://example.com/never-clicked"})
    code = r.json()["short_code"]
    stats = client.get(f"/api/analytics/{code}")
    assert stats.json()["total_clicks"] == 0


def test_analytics_for_unknown_code_404():
    _reset_db()
    r = client.get("/api/analytics/doesnotexist123")
    assert r.status_code == 404
'''


def run(task, context):
    req_type = context.get("requirement_type")

    if req_type == "ambiguous":
        context.log("Ambiguous scenario: skipping test generation (no code was generated).")
        return {"generated": False, "reason": "ambiguous requirement — design-only output"}

    project_dir = context.get("project_dir")
    if not project_dir:
        raise RuntimeError("No project_dir in context; codegen must run before test generation.")

    if req_type == "greenfield":
        path = os.path.join(project_dir, "tests", "test_edge_cases.py")
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w") as f:
            f.write(EDGE_CASE_TESTS)
        context.log(f"Added edge-case tests at {path}")
        return {"generated": True, "file": path}

    # brownfield: the rate-limit regression test was already added by the
    # codegen agent alongside the patch (kept together so the patch and its
    # regression test land atomically); confirm it's present.
    test_file = os.path.join(project_dir, "tests", "test_rate_limit.py")
    if not os.path.exists(test_file):
        raise RuntimeError("Expected regression test for brownfield patch was not found.")
    context.log(f"Confirmed regression test present at {test_file}")
    return {"generated": True, "file": test_file, "note": "added atomically with the patch"}
